---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
data:
  USER_HOST: "user"
  CART_HOST: "cart"
  AMQP_HOST: "rabbitmq"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    name: payment
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: payment
      tier: app
  template:
    metadata:
      labels:
        name: payment
        tier: app
    spec:
      containers:
      - name: payment
        imagePullPolicy: Always
        image: techworldwithsiva/payment:v1
        envFrom:
        - configMapRef:
            name: payment-config
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
spec:
  selector:
    name: payment
    tier: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080