apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eks-read-access
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - services
  - deployments
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: iam-user-read-access
subjects:
- kind: User
  name: roboshop-admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: eks-read-access
  apiGroup: rbac.authorization.k8s.io