---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: roboshop
data:
  MYSQL_DATABASE: "cities"
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: roboshop
type: Opaque
data:
  MYSQL_USER: c2hpcHBpbmc=
  MYSQL_PASSWORD: c2VjcmV0
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: roboshop
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  namespace: roboshop
spec:
  serviceName: mysql-service
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: techworldwithsiva/mysql:k8
        args:
        - "--ignore-db-dir=lost+found"
        envFrom:
        - configMapRef:
            name: mysql-config
        - secretRef:
            name: mysql-secret
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: ebs-sc